# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-22 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, max_length=255, null=True, upload_to='logos')),
                ('founded_on', models.DateField()),
                ('website', models.URLField(max_length=255)),
                ('linkedin_url', models.URLField(max_length=255)),
                ('twitter_url', models.URLField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Amount invested')),
                ('stage', models.PositiveIntegerField(choices=[(1, 'Series A'), (2, 'Series B'), (3, 'Series C'), (4, 'Series D'), (5, 'Series E'), (6, 'Series F')], default=1)),
                ('company', models.ForeignKey(help_text='Company being invested in', on_delete=django.db.models.deletion.CASCADE, related_name='investors', to='company.Company')),
                ('investor', models.ForeignKey(help_text='Company that invested', on_delete=django.db.models.deletion.CASCADE, related_name='investees', to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
    ]
